// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/disk_manager/internal/pkg/services/disks/protos/create_empty_disk_task.proto

package protos

import (
	_ "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEmptyDiskTaskState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateEmptyDiskTaskState) Reset() {
	*x = CreateEmptyDiskTaskState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmptyDiskTaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyDiskTaskState) ProtoMessage() {}

func (x *CreateEmptyDiskTaskState) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyDiskTaskState.ProtoReflect.Descriptor instead.
func (*CreateEmptyDiskTaskState) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescGZIP(), []int{0}
}

var File_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto protoreflect.FileDescriptor

var file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDesc = []byte{
	0x0a, 0x52, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x1a, 0x4e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x44, 0x69, 0x73,
	0x6b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6e, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescOnce sync.Once
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescData = file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDesc
)

func file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescGZIP() []byte {
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescOnce.Do(func() {
		file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescData)
	})
	return file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDescData
}

var file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_goTypes = []interface{}{
	(*CreateEmptyDiskTaskState)(nil), // 0: disks.CreateEmptyDiskTaskState
}
var file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_init()
}
func file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_init() {
	if File_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto != nil {
		return
	}
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_disk_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmptyDiskTaskState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_goTypes,
		DependencyIndexes: file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_depIdxs,
		MessageInfos:      file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_msgTypes,
	}.Build()
	File_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto = out.File
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_rawDesc = nil
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_goTypes = nil
	file_cloud_disk_manager_internal_pkg_services_disks_protos_create_empty_disk_task_proto_depIdxs = nil
}
