// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/disk_manager/internal/pkg/services/pools/protos/create_base_disk_task.proto

package protos

import (
	types "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBaseDiskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcImageId                          string      `protobuf:"bytes,1,opt,name=SrcImageId,proto3" json:"SrcImageId,omitempty"`
	SrcDisk                             *types.Disk `protobuf:"bytes,5,opt,name=SrcDisk,proto3" json:"SrcDisk,omitempty"`
	SrcDiskCheckpointId                 string      `protobuf:"bytes,6,opt,name=SrcDiskCheckpointId,proto3" json:"SrcDiskCheckpointId,omitempty"`
	BaseDisk                            *types.Disk `protobuf:"bytes,2,opt,name=BaseDisk,proto3" json:"BaseDisk,omitempty"`
	BaseDiskCheckpointId                string      `protobuf:"bytes,3,opt,name=BaseDiskCheckpointId,proto3" json:"BaseDiskCheckpointId,omitempty"`
	BaseDiskSize                        uint64      `protobuf:"varint,4,opt,name=BaseDiskSize,proto3" json:"BaseDiskSize,omitempty"`
	UseDataplaneTasksForLegacySnapshots bool        `protobuf:"varint,7,opt,name=UseDataplaneTasksForLegacySnapshots,proto3" json:"UseDataplaneTasksForLegacySnapshots,omitempty"`
}

func (x *CreateBaseDiskRequest) Reset() {
	*x = CreateBaseDiskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBaseDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseDiskRequest) ProtoMessage() {}

func (x *CreateBaseDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseDiskRequest.ProtoReflect.Descriptor instead.
func (*CreateBaseDiskRequest) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBaseDiskRequest) GetSrcImageId() string {
	if x != nil {
		return x.SrcImageId
	}
	return ""
}

func (x *CreateBaseDiskRequest) GetSrcDisk() *types.Disk {
	if x != nil {
		return x.SrcDisk
	}
	return nil
}

func (x *CreateBaseDiskRequest) GetSrcDiskCheckpointId() string {
	if x != nil {
		return x.SrcDiskCheckpointId
	}
	return ""
}

func (x *CreateBaseDiskRequest) GetBaseDisk() *types.Disk {
	if x != nil {
		return x.BaseDisk
	}
	return nil
}

func (x *CreateBaseDiskRequest) GetBaseDiskCheckpointId() string {
	if x != nil {
		return x.BaseDiskCheckpointId
	}
	return ""
}

func (x *CreateBaseDiskRequest) GetBaseDiskSize() uint64 {
	if x != nil {
		return x.BaseDiskSize
	}
	return 0
}

func (x *CreateBaseDiskRequest) GetUseDataplaneTasksForLegacySnapshots() bool {
	if x != nil {
		return x.UseDataplaneTasksForLegacySnapshots
	}
	return false
}

type CreateBaseDiskTaskState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step uint32 `protobuf:"varint,2,opt,name=Step,proto3" json:"Step,omitempty"`
}

func (x *CreateBaseDiskTaskState) Reset() {
	*x = CreateBaseDiskTaskState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBaseDiskTaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseDiskTaskState) ProtoMessage() {}

func (x *CreateBaseDiskTaskState) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseDiskTaskState.ProtoReflect.Descriptor instead.
func (*CreateBaseDiskTaskState) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBaseDiskTaskState) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

var File_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto protoreflect.FileDescriptor

var file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDesc = []byte{
	0x0a, 0x51, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x1a, 0x31, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x02,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x72, 0x63, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x72, 0x63,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x53, 0x72, 0x63, 0x44, 0x69,
	0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x07, 0x53, 0x72, 0x63, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x30,
	0x0a, 0x13, 0x53, 0x72, 0x63, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x53, 0x72, 0x63,
	0x44, 0x69, 0x73, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x27, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52,
	0x08, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x32, 0x0a, 0x14, 0x42, 0x61, 0x73,
	0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73,
	0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x50, 0x0a, 0x23, 0x55, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x46, 0x6f, 0x72, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x23,
	0x55, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x46, 0x6f, 0x72, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x74,
	0x65, 0x70, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6e, 0x62,
	0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescOnce sync.Once
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescData = file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDesc
)

func file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescGZIP() []byte {
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescOnce.Do(func() {
		file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescData)
	})
	return file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDescData
}

var file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_goTypes = []interface{}{
	(*CreateBaseDiskRequest)(nil),   // 0: pools.CreateBaseDiskRequest
	(*CreateBaseDiskTaskState)(nil), // 1: pools.CreateBaseDiskTaskState
	(*types.Disk)(nil),              // 2: types.Disk
}
var file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_depIdxs = []int32{
	2, // 0: pools.CreateBaseDiskRequest.SrcDisk:type_name -> types.Disk
	2, // 1: pools.CreateBaseDiskRequest.BaseDisk:type_name -> types.Disk
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_init()
}
func file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_init() {
	if File_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBaseDiskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBaseDiskTaskState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_goTypes,
		DependencyIndexes: file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_depIdxs,
		MessageInfos:      file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_msgTypes,
	}.Build()
	File_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto = out.File
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_rawDesc = nil
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_goTypes = nil
	file_cloud_disk_manager_internal_pkg_services_pools_protos_create_base_disk_task_proto_depIdxs = nil
}
