// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/disk_manager/internal/pkg/dataplane/protos/transfer_from_disk_to_disk_task.proto

package protos

import (
	types "github.com/ydb-platform/nbs/cloud/disk_manager/internal/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferFromDiskToDiskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcDisk                 *types.Disk `protobuf:"bytes,1,opt,name=SrcDisk,proto3" json:"SrcDisk,omitempty"`
	SrcDiskCheckpointId     string      `protobuf:"bytes,2,opt,name=SrcDiskCheckpointId,proto3" json:"SrcDiskCheckpointId,omitempty"`
	DstDisk                 *types.Disk `protobuf:"bytes,3,opt,name=DstDisk,proto3" json:"DstDisk,omitempty"`
	SrcDiskBaseCheckpointId string      `protobuf:"bytes,4,opt,name=SrcDiskBaseCheckpointId,proto3" json:"SrcDiskBaseCheckpointId,omitempty"`
	FillGeneration          uint64      `protobuf:"varint,5,opt,name=FillGeneration,proto3" json:"FillGeneration,omitempty"`
	FillSeqNumber           uint64      `protobuf:"varint,6,opt,name=FillSeqNumber,proto3" json:"FillSeqNumber,omitempty"`
}

func (x *TransferFromDiskToDiskRequest) Reset() {
	*x = TransferFromDiskToDiskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFromDiskToDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFromDiskToDiskRequest) ProtoMessage() {}

func (x *TransferFromDiskToDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFromDiskToDiskRequest.ProtoReflect.Descriptor instead.
func (*TransferFromDiskToDiskRequest) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescGZIP(), []int{0}
}

func (x *TransferFromDiskToDiskRequest) GetSrcDisk() *types.Disk {
	if x != nil {
		return x.SrcDisk
	}
	return nil
}

func (x *TransferFromDiskToDiskRequest) GetSrcDiskCheckpointId() string {
	if x != nil {
		return x.SrcDiskCheckpointId
	}
	return ""
}

func (x *TransferFromDiskToDiskRequest) GetDstDisk() *types.Disk {
	if x != nil {
		return x.DstDisk
	}
	return nil
}

func (x *TransferFromDiskToDiskRequest) GetSrcDiskBaseCheckpointId() string {
	if x != nil {
		return x.SrcDiskBaseCheckpointId
	}
	return ""
}

func (x *TransferFromDiskToDiskRequest) GetFillGeneration() uint64 {
	if x != nil {
		return x.FillGeneration
	}
	return 0
}

func (x *TransferFromDiskToDiskRequest) GetFillSeqNumber() uint64 {
	if x != nil {
		return x.FillSeqNumber
	}
	return 0
}

type TransferFromDiskToDiskTaskState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MilestoneChunkIndex   uint32  `protobuf:"varint,2,opt,name=MilestoneChunkIndex,proto3" json:"MilestoneChunkIndex,omitempty"`
	TransferredChunkCount uint32  `protobuf:"varint,5,opt,name=TransferredChunkCount,proto3" json:"TransferredChunkCount,omitempty"`
	Progress              float64 `protobuf:"fixed64,4,opt,name=Progress,proto3" json:"Progress,omitempty"`
	ChunkCount            uint32  `protobuf:"varint,3,opt,name=ChunkCount,proto3" json:"ChunkCount,omitempty"`
}

func (x *TransferFromDiskToDiskTaskState) Reset() {
	*x = TransferFromDiskToDiskTaskState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFromDiskToDiskTaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFromDiskToDiskTaskState) ProtoMessage() {}

func (x *TransferFromDiskToDiskTaskState) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFromDiskToDiskTaskState.ProtoReflect.Descriptor instead.
func (*TransferFromDiskToDiskTaskState) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescGZIP(), []int{1}
}

func (x *TransferFromDiskToDiskTaskState) GetMilestoneChunkIndex() uint32 {
	if x != nil {
		return x.MilestoneChunkIndex
	}
	return 0
}

func (x *TransferFromDiskToDiskTaskState) GetTransferredChunkCount() uint32 {
	if x != nil {
		return x.TransferredChunkCount
	}
	return 0
}

func (x *TransferFromDiskToDiskTaskState) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TransferFromDiskToDiskTaskState) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type TransferFromDiskToDiskMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress float64 `protobuf:"fixed64,1,opt,name=Progress,proto3" json:"Progress,omitempty"`
}

func (x *TransferFromDiskToDiskMetadata) Reset() {
	*x = TransferFromDiskToDiskMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFromDiskToDiskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFromDiskToDiskMetadata) ProtoMessage() {}

func (x *TransferFromDiskToDiskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFromDiskToDiskMetadata.ProtoReflect.Descriptor instead.
func (*TransferFromDiskToDiskMetadata) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescGZIP(), []int{2}
}

func (x *TransferFromDiskToDiskMetadata) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto protoreflect.FileDescriptor

var file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDesc = []byte{
	0x0a, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x74, 0x6f, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x1a, 0x31, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x1d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x6f, 0x44, 0x69, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x53, 0x72, 0x63, 0x44,
	0x69, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x07, 0x53, 0x72, 0x63, 0x44, 0x69, 0x73, 0x6b, 0x12,
	0x30, 0x0a, 0x13, 0x53, 0x72, 0x63, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x53, 0x72,
	0x63, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x07, 0x44, 0x73, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52,
	0x07, 0x44, 0x73, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x38, 0x0a, 0x17, 0x53, 0x72, 0x63, 0x44,
	0x69, 0x73, 0x6b, 0x42, 0x61, 0x73, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x53, 0x72, 0x63, 0x44, 0x69,
	0x73, 0x6b, 0x42, 0x61, 0x73, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x46, 0x69, 0x6c, 0x6c,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x69,
	0x6c, 0x6c, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x46, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0xc5, 0x01, 0x0a, 0x1f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x72, 0x6f,
	0x6d, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x6f, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x34, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72,
	0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x1e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x6f, 0x44, 0x69,
	0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2f, 0x6e, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b,
	0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescOnce sync.Once
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescData = file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDesc
)

func file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescGZIP() []byte {
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescOnce.Do(func() {
		file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescData)
	})
	return file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDescData
}

var file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_goTypes = []interface{}{
	(*TransferFromDiskToDiskRequest)(nil),   // 0: dataplane.TransferFromDiskToDiskRequest
	(*TransferFromDiskToDiskTaskState)(nil), // 1: dataplane.TransferFromDiskToDiskTaskState
	(*TransferFromDiskToDiskMetadata)(nil),  // 2: dataplane.TransferFromDiskToDiskMetadata
	(*types.Disk)(nil),                      // 3: types.Disk
}
var file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_depIdxs = []int32{
	3, // 0: dataplane.TransferFromDiskToDiskRequest.SrcDisk:type_name -> types.Disk
	3, // 1: dataplane.TransferFromDiskToDiskRequest.DstDisk:type_name -> types.Disk
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_init()
}
func file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_init() {
	if File_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFromDiskToDiskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFromDiskToDiskTaskState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFromDiskToDiskMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_goTypes,
		DependencyIndexes: file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_depIdxs,
		MessageInfos:      file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_msgTypes,
	}.Build()
	File_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto = out.File
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_rawDesc = nil
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_goTypes = nil
	file_cloud_disk_manager_internal_pkg_dataplane_protos_transfer_from_disk_to_disk_task_proto_depIdxs = nil
}
