// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: yandex/cloud/priv/disk_manager/v1/placement_group.proto

package disk_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlacementStrategy int32

const (
	PlacementStrategy_PLACEMENT_STRATEGY_UNSPECIFIED PlacementStrategy = 0
	PlacementStrategy_PLACEMENT_STRATEGY_SPREAD      PlacementStrategy = 1
	PlacementStrategy_PLACEMENT_STRATEGY_PARTITION   PlacementStrategy = 2
)

// Enum value maps for PlacementStrategy.
var (
	PlacementStrategy_name = map[int32]string{
		0: "PLACEMENT_STRATEGY_UNSPECIFIED",
		1: "PLACEMENT_STRATEGY_SPREAD",
		2: "PLACEMENT_STRATEGY_PARTITION",
	}
	PlacementStrategy_value = map[string]int32{
		"PLACEMENT_STRATEGY_UNSPECIFIED": 0,
		"PLACEMENT_STRATEGY_SPREAD":      1,
		"PLACEMENT_STRATEGY_PARTITION":   2,
	}
)

func (x PlacementStrategy) Enum() *PlacementStrategy {
	p := new(PlacementStrategy)
	*p = x
	return p
}

func (x PlacementStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_enumTypes[0].Descriptor()
}

func (PlacementStrategy) Type() protoreflect.EnumType {
	return &file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_enumTypes[0]
}

func (x PlacementStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementStrategy.Descriptor instead.
func (PlacementStrategy) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescGZIP(), []int{0}
}

type GroupId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneId  string `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *GroupId) Reset() {
	*x = GroupId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupId) ProtoMessage() {}

func (x *GroupId) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupId.ProtoReflect.Descriptor instead.
func (*GroupId) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescGZIP(), []int{0}
}

func (x *GroupId) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GroupId) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type PlacementGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId                 *GroupId          `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PlacementStrategy       PlacementStrategy `protobuf:"varint,2,opt,name=placement_strategy,json=placementStrategy,proto3,enum=yandex.cloud.priv.disk_manager.v1.PlacementStrategy" json:"placement_strategy,omitempty"`
	DiskIds                 []string          `protobuf:"bytes,3,rep,name=disk_ids,json=diskIds,proto3" json:"disk_ids,omitempty"`
	Racks                   []string          `protobuf:"bytes,4,rep,name=racks,proto3" json:"racks,omitempty"`
	PlacementPartitionCount uint32            `protobuf:"varint,6,opt,name=placement_partition_count,json=placementPartitionCount,proto3" json:"placement_partition_count,omitempty"`
}

func (x *PlacementGroup) Reset() {
	*x = PlacementGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlacementGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementGroup) ProtoMessage() {}

func (x *PlacementGroup) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementGroup.ProtoReflect.Descriptor instead.
func (*PlacementGroup) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescGZIP(), []int{1}
}

func (x *PlacementGroup) GetGroupId() *GroupId {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *PlacementGroup) GetPlacementStrategy() PlacementStrategy {
	if x != nil {
		return x.PlacementStrategy
	}
	return PlacementStrategy_PLACEMENT_STRATEGY_UNSPECIFIED
}

func (x *PlacementGroup) GetDiskIds() []string {
	if x != nil {
		return x.DiskIds
	}
	return nil
}

func (x *PlacementGroup) GetRacks() []string {
	if x != nil {
		return x.Racks
	}
	return nil
}

func (x *PlacementGroup) GetPlacementPartitionCount() uint32 {
	if x != nil {
		return x.PlacementPartitionCount
	}
	return 0
}

var File_yandex_cloud_priv_disk_manager_v1_placement_group_proto protoreflect.FileDescriptor

var file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDesc = []byte{
	0x0a, 0x37, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x64, 0x69, 0x73,
	0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x07,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0xaf, 0x02, 0x0a, 0x0e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x45,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x63, 0x0a, 0x12, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x34, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x11, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69,
	0x73, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x3a, 0x0a, 0x19, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x17,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x2a, 0x78, 0x0a,
	0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x12, 0x22, 0x0a, 0x1e, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59, 0x5f, 0x53, 0x50, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59, 0x5f, 0x50, 0x41, 0x52, 0x54,
	0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x63, 0x5a, 0x61, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x6e, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73,
	0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61,
	0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f,
	0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescOnce sync.Once
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescData = file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDesc
)

func file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescGZIP() []byte {
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescData)
	})
	return file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDescData
}

var file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_goTypes = []interface{}{
	(PlacementStrategy)(0), // 0: yandex.cloud.priv.disk_manager.v1.PlacementStrategy
	(*GroupId)(nil),        // 1: yandex.cloud.priv.disk_manager.v1.GroupId
	(*PlacementGroup)(nil), // 2: yandex.cloud.priv.disk_manager.v1.PlacementGroup
}
var file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_depIdxs = []int32{
	1, // 0: yandex.cloud.priv.disk_manager.v1.PlacementGroup.group_id:type_name -> yandex.cloud.priv.disk_manager.v1.GroupId
	0, // 1: yandex.cloud.priv.disk_manager.v1.PlacementGroup.placement_strategy:type_name -> yandex.cloud.priv.disk_manager.v1.PlacementStrategy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_init() }
func file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_init() {
	if File_yandex_cloud_priv_disk_manager_v1_placement_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlacementGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_msgTypes,
	}.Build()
	File_yandex_cloud_priv_disk_manager_v1_placement_group_proto = out.File
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_rawDesc = nil
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_goTypes = nil
	file_yandex_cloud_priv_disk_manager_v1_placement_group_proto_depIdxs = nil
}
