// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/disk_manager/internal/pkg/persistence/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistenceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint              *string   `protobuf:"bytes,1,req,name=Endpoint" json:"Endpoint,omitempty"`
	Database              *string   `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	RootPath              *string   `protobuf:"bytes,3,opt,name=RootPath" json:"RootPath,omitempty"`
	Secure                *bool     `protobuf:"varint,4,opt,name=Secure" json:"Secure,omitempty"`
	RootCertsFile         *string   `protobuf:"bytes,5,opt,name=RootCertsFile" json:"RootCertsFile,omitempty"`
	ConnectionTimeout     *string   `protobuf:"bytes,6,opt,name=ConnectionTimeout,def=10s" json:"ConnectionTimeout,omitempty"`
	DisableAuthentication *bool     `protobuf:"varint,7,opt,name=DisableAuthentication" json:"DisableAuthentication,omitempty"`
	S3Config              *S3Config `protobuf:"bytes,8,opt,name=S3Config" json:"S3Config,omitempty"`
	// Timeout for YDB call, i.e. BeginTransaction, Execute, Commit, etc.
	CallTimeout *string `protobuf:"bytes,9,opt,name=CallTimeout,def=600s" json:"CallTimeout,omitempty"`
}

// Default values for PersistenceConfig fields.
const (
	Default_PersistenceConfig_ConnectionTimeout = string("10s")
	Default_PersistenceConfig_CallTimeout       = string("600s")
)

func (x *PersistenceConfig) Reset() {
	*x = PersistenceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistenceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistenceConfig) ProtoMessage() {}

func (x *PersistenceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistenceConfig.ProtoReflect.Descriptor instead.
func (*PersistenceConfig) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *PersistenceConfig) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *PersistenceConfig) GetDatabase() string {
	if x != nil && x.Database != nil {
		return *x.Database
	}
	return ""
}

func (x *PersistenceConfig) GetRootPath() string {
	if x != nil && x.RootPath != nil {
		return *x.RootPath
	}
	return ""
}

func (x *PersistenceConfig) GetSecure() bool {
	if x != nil && x.Secure != nil {
		return *x.Secure
	}
	return false
}

func (x *PersistenceConfig) GetRootCertsFile() string {
	if x != nil && x.RootCertsFile != nil {
		return *x.RootCertsFile
	}
	return ""
}

func (x *PersistenceConfig) GetConnectionTimeout() string {
	if x != nil && x.ConnectionTimeout != nil {
		return *x.ConnectionTimeout
	}
	return Default_PersistenceConfig_ConnectionTimeout
}

func (x *PersistenceConfig) GetDisableAuthentication() bool {
	if x != nil && x.DisableAuthentication != nil {
		return *x.DisableAuthentication
	}
	return false
}

func (x *PersistenceConfig) GetS3Config() *S3Config {
	if x != nil {
		return x.S3Config
	}
	return nil
}

func (x *PersistenceConfig) GetCallTimeout() string {
	if x != nil && x.CallTimeout != nil {
		return *x.CallTimeout
	}
	return Default_PersistenceConfig_CallTimeout
}

type S3Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint            *string `protobuf:"bytes,1,req,name=Endpoint" json:"Endpoint,omitempty"`
	Region              *string `protobuf:"bytes,2,req,name=Region" json:"Region,omitempty"`
	CredentialsFilePath *string `protobuf:"bytes,3,req,name=CredentialsFilePath" json:"CredentialsFilePath,omitempty"`
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *S3Config) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *S3Config) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *S3Config) GetCredentialsFilePath() string {
	if x != nil && x.CredentialsFilePath != nil {
		return *x.CredentialsFilePath
	}
	return ""
}

var File_cloud_disk_manager_internal_pkg_persistence_config_config_proto protoreflect.FileDescriptor

var file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xe9,
	0x02, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x6f, 0x6f, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65, 0x72,
	0x74, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x3a, 0x03, 0x31, 0x30, 0x73, 0x52, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x15, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x31, 0x0a, 0x08, 0x53, 0x33, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x53, 0x33, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x53, 0x33, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x26, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x04, 0x36, 0x30, 0x30, 0x73, 0x52, 0x0b, 0x43,
	0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x70, 0x0a, 0x08, 0x53, 0x33,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x13, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x50, 0x5a, 0x4e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6e, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
}

var (
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescOnce sync.Once
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescData = file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDesc
)

func file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescGZIP() []byte {
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescOnce.Do(func() {
		file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescData)
	})
	return file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDescData
}

var file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_goTypes = []interface{}{
	(*PersistenceConfig)(nil), // 0: persistence.PersistenceConfig
	(*S3Config)(nil),          // 1: persistence.S3Config
}
var file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_depIdxs = []int32{
	1, // 0: persistence.PersistenceConfig.S3Config:type_name -> persistence.S3Config
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_init() }
func file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_init() {
	if File_cloud_disk_manager_internal_pkg_persistence_config_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistenceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S3Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_goTypes,
		DependencyIndexes: file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_depIdxs,
		MessageInfos:      file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_msgTypes,
	}.Build()
	File_cloud_disk_manager_internal_pkg_persistence_config_config_proto = out.File
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_rawDesc = nil
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_goTypes = nil
	file_cloud_disk_manager_internal_pkg_persistence_config_config_proto_depIdxs = nil
}
