// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.0
// source: cloud/disk_manager/internal/pkg/clients/nfs/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []string `protobuf:"bytes,1,rep,name=Endpoints" json:"Endpoints,omitempty"`
}

func (x *Zone) Reset() {
	*x = Zone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Zone) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ClientConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zones                 map[string]*Zone `protobuf:"bytes,1,rep,name=Zones" json:"Zones,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RootCertsFile         *string          `protobuf:"bytes,2,opt,name=RootCertsFile" json:"RootCertsFile,omitempty"`
	Insecure              *bool            `protobuf:"varint,3,opt,name=Insecure" json:"Insecure,omitempty"`
	DisableAuthentication *bool            `protobuf:"varint,4,opt,name=DisableAuthentication" json:"DisableAuthentication,omitempty"`
	DurableClientTimeout  *string          `protobuf:"bytes,5,opt,name=DurableClientTimeout,def=20s" json:"DurableClientTimeout,omitempty"`
}

// Default values for ClientConfig fields.
const (
	Default_ClientConfig_DurableClientTimeout = string("20s")
)

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetZones() map[string]*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ClientConfig) GetRootCertsFile() string {
	if x != nil && x.RootCertsFile != nil {
		return *x.RootCertsFile
	}
	return ""
}

func (x *ClientConfig) GetInsecure() bool {
	if x != nil && x.Insecure != nil {
		return *x.Insecure
	}
	return false
}

func (x *ClientConfig) GetDisableAuthentication() bool {
	if x != nil && x.DisableAuthentication != nil {
		return *x.DisableAuthentication
	}
	return false
}

func (x *ClientConfig) GetDurableClientTimeout() string {
	if x != nil && x.DurableClientTimeout != nil {
		return *x.DurableClientTimeout
	}
	return Default_ClientConfig_DurableClientTimeout
}

var File_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto protoreflect.FileDescriptor

var file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6e, 0x66, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6e, 0x66, 0x73, 0x22, 0x24, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xb8, 0x02, 0x0a,
	0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x32, 0x0a,
	0x05, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e,
	0x66, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x5a, 0x6f, 0x6e, 0x65,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65,
	0x72, 0x74, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x6e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x14, 0x44, 0x75, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x03, 0x32, 0x30, 0x73, 0x52, 0x14, 0x44, 0x75,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x1a, 0x43, 0x0a, 0x0a, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x6e, 0x66, 0x73, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x6e, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x69, 0x73,
	0x6b, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6e,
	0x66, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
}

var (
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescOnce sync.Once
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescData = file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDesc
)

func file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescGZIP() []byte {
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescOnce.Do(func() {
		file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescData)
	})
	return file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDescData
}

var file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_goTypes = []interface{}{
	(*Zone)(nil),         // 0: nfs.Zone
	(*ClientConfig)(nil), // 1: nfs.ClientConfig
	nil,                  // 2: nfs.ClientConfig.ZonesEntry
}
var file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_depIdxs = []int32{
	2, // 0: nfs.ClientConfig.Zones:type_name -> nfs.ClientConfig.ZonesEntry
	0, // 1: nfs.ClientConfig.ZonesEntry.value:type_name -> nfs.Zone
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_init() }
func file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_init() {
	if File_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_goTypes,
		DependencyIndexes: file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_depIdxs,
		MessageInfos:      file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_msgTypes,
	}.Build()
	File_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto = out.File
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_rawDesc = nil
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_goTypes = nil
	file_cloud_disk_manager_internal_pkg_clients_nfs_config_config_proto_depIdxs = nil
}
